services:

  cicd_test_project:
    build: .
    container_name: test_cicd
    ports:
      - "50051:50051"
    networks:
      - cicd

  postgres-db:
    container_name: postgres-db
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - cicd


networks:
  cicd:
    driver: bridge

volumes:
  db:
    driver: local