name: CI - Build and Test with Docker

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t ci_cd_app .

      - name: Run services with docker-compose
        run: docker compose up -d

      - name: Wait for services to be healthy
        run: |
          echo "Waiting for services..."
          sleep 15
          docker ps -a

      - name: Test application endpoint
        run: |
          curl --fail http://localhost:50051/ping || exit 1

      - name: Stop containers
        run: docker compose down
